/* Generated by `cargo run -p abi-header`. Do not edit by hand.
 *
 * The tessella capture-stream ABI, revision 2.
 *
 * The Rust definitions in tessella-capture-abi are the source of truth; this is the C view of
 * them. Every size and offset asserted below was taken from the Rust types at generation time,
 * so a struct here that does not match will fail to compile rather than misread the stream.
 */
#ifndef TESSELLA_CAPTURE_ABI_H
#define TESSELLA_CAPTURE_ABI_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* C++ spells the assertion differently, and older C has no keyword at all. */
#if defined(__cplusplus)
#define TSL_ASSERT(cond, msg) static_assert(cond, msg)
#elif defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L
#define TSL_ASSERT(cond, msg) _Static_assert(cond, msg)
#else
#define TSL_ASSERT(cond, msg)
#endif

#if defined(__cplusplus)
#define TSL_ALIGNOF(type) alignof(type)
#else
#define TSL_ALIGNOF(type) _Alignof(type)
#endif

#define TSL_ABI_REV 2u
#define TSL_RECORD_ALIGN 16u
#define TSL_RECORD_FLAG_SKIP 1u
#define TSL_TEXTURE_RECT_CAP 4u
#define TSL_PAYLOAD_ALIGN 8u
#define TSL_MAX_VIEWS 8u

/* Bits in tsl_view_slot.flags. An unpublished slot is not a hidden view: it is a view
 * the consumer has never mentioned, and the producer must not read a camera out of it. */
#define TSL_VIEW_FLAG_PUBLISHED 1u
#define TSL_VIEW_FLAG_VISIBLE 2u

/* Envelope kinds carried on the ring. */
typedef enum tsl_envelope_kind {
    TSL_ENVELOPE_KIND_GEOMETRY_ADD = 1,
    TSL_ENVELOPE_KIND_GEOMETRY_REMOVE = 2,
    TSL_ENVELOPE_KIND_VIEW_USE = 3,
    TSL_ENVELOPE_KIND_VIEW_RELEASE = 4,
    TSL_ENVELOPE_KIND_UBO_UPDATE = 5,
    TSL_ENVELOPE_KIND_TEXTURE_UPDATE = 6,
    TSL_ENVELOPE_KIND_CAMERA_UPDATE = 7,
    TSL_ENVELOPE_KIND_ORDER_UPDATE = 8,
    TSL_ENVELOPE_KIND_STENCIL_TILES = 9,
    TSL_ENVELOPE_KIND_VIEW_DECLARE = 10,
    TSL_ENVELOPE_KIND_VIEW_UNDECLARE = 11,
    TSL_ENVELOPE_KIND_MESH_ADD = 12,
} tsl_envelope_kind;

/* Why geometry was announced. A steady stream of ATTRIBUTES_MODIFIED on a static scene is a */
/* visible bug, not a hint. */
typedef enum tsl_add_reason {
    TSL_ADD_REASON_CREATED = 0,
    TSL_ADD_REASON_INDEX_DATA_REPLACED = 1,
    TSL_ADD_REASON_ATTRIBUTES_REPLACED = 2,
    TSL_ADD_REASON_ATTRIBUTES_MODIFIED = 3,
} tsl_add_reason;

/* What a mesh's bytes are. A consumer meeting a value it does not know must skip the mesh rather */
/* than guess at the bytes. */
typedef enum tsl_mesh_format {
    TSL_MESH_FORMAT_GLB = 1,
} tsl_mesh_format;

/* Which side owns a view's camera. Declared per view at tsl_view_declare. */
typedef enum tsl_camera_mode {
    TSL_CAMERA_MODE_PRODUCER = 0,
    TSL_CAMERA_MODE_CONSUMER = 1,
} tsl_camera_mode;

/* Pixel format of a texture. */
typedef enum tsl_texture_pixel_type {
    TSL_TEXTURE_PIXEL_TYPE_RGBA = 0,
    TSL_TEXTURE_PIXEL_TYPE_ALPHA = 1,
    TSL_TEXTURE_PIXEL_TYPE_STENCIL = 2,
    TSL_TEXTURE_PIXEL_TYPE_DEPTH = 3,
    TSL_TEXTURE_PIXEL_TYPE_LUMINANCE = 4,
} tsl_texture_pixel_type;

/*
 * How many bytes one pixel of a format occupies.
 *
 * Every channel is one byte on this stream: mbgl's channel storage size is per channel
 * data type, and nothing here sends anything but unsigned bytes. So a whole-texture
 * upload -- rect_count of zero -- carries width * height * this many bytes, and a
 * rectangle's rows are w * this many bytes apart.
 */
static inline uint32_t tsl_texture_pixel_size(int format) {
    switch (format) {
    case TSL_TEXTURE_PIXEL_TYPE_RGBA: return 4;
    case TSL_TEXTURE_PIXEL_TYPE_ALPHA: return 1;
    case TSL_TEXTURE_PIXEL_TYPE_STENCIL: return 1;
    case TSL_TEXTURE_PIXEL_TYPE_DEPTH: return 1;
    case TSL_TEXTURE_PIXEL_TYPE_LUMINANCE: return 1;
    default: return 0;
    }
}

/* The type of a vertex attribute. */
typedef enum tsl_attribute_data_type {
    TSL_ATTRIBUTE_DATA_TYPE_BYTE = 0,
    TSL_ATTRIBUTE_DATA_TYPE_BYTE2 = 1,
    TSL_ATTRIBUTE_DATA_TYPE_BYTE3 = 2,
    TSL_ATTRIBUTE_DATA_TYPE_BYTE4 = 3,
    TSL_ATTRIBUTE_DATA_TYPE_UBYTE = 4,
    TSL_ATTRIBUTE_DATA_TYPE_UBYTE2 = 5,
    TSL_ATTRIBUTE_DATA_TYPE_UBYTE3 = 6,
    TSL_ATTRIBUTE_DATA_TYPE_UBYTE4 = 7,
    TSL_ATTRIBUTE_DATA_TYPE_SHORT = 8,
    TSL_ATTRIBUTE_DATA_TYPE_SHORT2 = 9,
    TSL_ATTRIBUTE_DATA_TYPE_SHORT3 = 10,
    TSL_ATTRIBUTE_DATA_TYPE_SHORT4 = 11,
    TSL_ATTRIBUTE_DATA_TYPE_USHORT = 12,
    TSL_ATTRIBUTE_DATA_TYPE_USHORT2 = 13,
    TSL_ATTRIBUTE_DATA_TYPE_USHORT3 = 14,
    TSL_ATTRIBUTE_DATA_TYPE_USHORT4 = 15,
    TSL_ATTRIBUTE_DATA_TYPE_USHORT8 = 16,
    TSL_ATTRIBUTE_DATA_TYPE_INT = 17,
    TSL_ATTRIBUTE_DATA_TYPE_INT2 = 18,
    TSL_ATTRIBUTE_DATA_TYPE_INT3 = 19,
    TSL_ATTRIBUTE_DATA_TYPE_INT4 = 20,
    TSL_ATTRIBUTE_DATA_TYPE_UINT = 21,
    TSL_ATTRIBUTE_DATA_TYPE_UINT2 = 22,
    TSL_ATTRIBUTE_DATA_TYPE_UINT3 = 23,
    TSL_ATTRIBUTE_DATA_TYPE_UINT4 = 24,
    TSL_ATTRIBUTE_DATA_TYPE_FLOAT = 25,
    TSL_ATTRIBUTE_DATA_TYPE_FLOAT2 = 26,
    TSL_ATTRIBUTE_DATA_TYPE_FLOAT3 = 27,
    TSL_ATTRIBUTE_DATA_TYPE_FLOAT4 = 28,
    TSL_ATTRIBUTE_DATA_TYPE_INVALID = 255,
} tsl_attribute_data_type;

/* Shader family. */
typedef enum tsl_builtin {
    TSL_BUILTIN_NONE = 0,
    TSL_BUILTIN_PRELUDE = 1,
    TSL_BUILTIN_CLIPPING_MASK_PROGRAM = 2,
    TSL_BUILTIN_BACKGROUND_SHADER = 3,
    TSL_BUILTIN_BACKGROUND_PATTERN_SHADER = 4,
    TSL_BUILTIN_CIRCLE_SHADER = 5,
    TSL_BUILTIN_COLLISION_BOX_SHADER = 6,
    TSL_BUILTIN_COLLISION_CIRCLE_SHADER = 7,
    TSL_BUILTIN_CUSTOM_GEOMETRY_SHADER = 8,
    TSL_BUILTIN_CUSTOM_SYMBOL_ICON_SHADER = 9,
    TSL_BUILTIN_DEBUG_SHADER = 10,
    TSL_BUILTIN_FILL_SHADER = 11,
    TSL_BUILTIN_FILL_OUTLINE_SHADER = 12,
    TSL_BUILTIN_FILL_PATTERN_SHADER = 13,
    TSL_BUILTIN_FILL_OUTLINE_PATTERN_SHADER = 14,
    TSL_BUILTIN_FILL_OUTLINE_TRIANGULATED_SHADER = 15,
    TSL_BUILTIN_FILL_EXTRUSION_SHADER = 16,
    TSL_BUILTIN_FILL_EXTRUSION_INSTANCED_SHADER = 17,
    TSL_BUILTIN_FILL_EXTRUSION_PATTERN_SHADER = 18,
    TSL_BUILTIN_FILL_EXTRUSION_PATTERN_INSTANCED_SHADER = 19,
    TSL_BUILTIN_HEATMAP_SHADER = 20,
    TSL_BUILTIN_HEATMAP_TEXTURE_SHADER = 21,
    TSL_BUILTIN_HILLSHADE_PREPARE_SHADER = 22,
    TSL_BUILTIN_COLOR_RELIEF_SHADER = 23,
    TSL_BUILTIN_HILLSHADE_SHADER = 24,
    TSL_BUILTIN_LINE_SHADER = 25,
    TSL_BUILTIN_LINE_GRADIENT_SHADER = 26,
    TSL_BUILTIN_LINE_PATTERN_SHADER = 27,
    TSL_BUILTIN_LOCATION_INDICATOR_SHADER = 28,
    TSL_BUILTIN_LOCATION_INDICATOR_TEXTURED_SHADER = 29,
    TSL_BUILTIN_LINE_SDFSHADER = 30,
    TSL_BUILTIN_RASTER_SHADER = 31,
    TSL_BUILTIN_SYMBOL_ICON_SHADER = 32,
    TSL_BUILTIN_SYMBOL_SDFSHADER = 33,
    TSL_BUILTIN_SYMBOL_TEXT_AND_ICON_SHADER = 34,
    TSL_BUILTIN_WIDE_VECTOR_SHADER = 35,
} tsl_builtin;

/* Render pass is a mask; mbgl ORs these together. */
#define TSL_RENDER_PASS_NONE 0u
#define TSL_RENDER_PASS_OPAQUE 1u
#define TSL_RENDER_PASS_TRANSLUCENT 2u
#define TSL_RENDER_PASS_3D 4u

/* Per-drawable render state, also a mask. */
#define TSL_DRAW_FLAG_IS_3D 1u
#define TSL_DRAW_FLAG_ENABLE_STENCIL 2u
#define TSL_DRAW_FLAG_ENABLE_DEPTH 4u
#define TSL_DRAW_FLAG_ENABLE_COLOR 8u

/*
 * A tile address.
 *
 * Mirrors `TileId`.
 */
typedef struct tsl_tile_id {
    /* Canonical x. */
    uint32_t x;
    /* Canonical y. */
    uint32_t y;
    /* Canonical z. */
    uint8_t z;
    /* Zoom the tile is displayed at. */
    uint8_t overscaled_z;
    /* World copy, past the antimeridian. */
    int16_t wrap;
} tsl_tile_id;

TSL_ASSERT(sizeof(tsl_tile_id) == 12, "tsl_tile_id size differs from the Rust definition");
TSL_ASSERT(TSL_ALIGNOF(tsl_tile_id) == 4, "tsl_tile_id alignment differs from the Rust definition");
TSL_ASSERT(offsetof(tsl_tile_id, x) == 0, "tsl_tile_id.x moved");
TSL_ASSERT(offsetof(tsl_tile_id, y) == 4, "tsl_tile_id.y moved");
TSL_ASSERT(offsetof(tsl_tile_id, z) == 8, "tsl_tile_id.z moved");
TSL_ASSERT(offsetof(tsl_tile_id, overscaled_z) == 9, "tsl_tile_id.overscaled_z moved");
TSL_ASSERT(offsetof(tsl_tile_id, wrap) == 10, "tsl_tile_id.wrap moved");

/*
 * A rectangle in texture space.
 *
 * Mirrors `Rect16`.
 */
typedef struct tsl_rect {
    /* Left edge. */
    uint16_t x;
    /* Top edge. */
    uint16_t y;
    /* Width. */
    uint16_t w;
    /* Height. */
    uint16_t h;
} tsl_rect;

TSL_ASSERT(sizeof(tsl_rect) == 8, "tsl_rect size differs from the Rust definition");
TSL_ASSERT(TSL_ALIGNOF(tsl_rect) == 2, "tsl_rect alignment differs from the Rust definition");
TSL_ASSERT(offsetof(tsl_rect, x) == 0, "tsl_rect.x moved");
TSL_ASSERT(offsetof(tsl_rect, y) == 2, "tsl_rect.y moved");
TSL_ASSERT(offsetof(tsl_rect, w) == 4, "tsl_rect.w moved");
TSL_ASSERT(offsetof(tsl_rect, h) == 6, "tsl_rect.h moved");

/*
 * Pixel dimensions.
 *
 * Mirrors `Extent`.
 */
typedef struct tsl_extent {
    /* Width in pixels. */
    uint32_t width;
    /* Height in pixels. */
    uint32_t height;
} tsl_extent;

TSL_ASSERT(sizeof(tsl_extent) == 8, "tsl_extent size differs from the Rust definition");
TSL_ASSERT(TSL_ALIGNOF(tsl_extent) == 4, "tsl_extent alignment differs from the Rust definition");
TSL_ASSERT(offsetof(tsl_extent, width) == 0, "tsl_extent.width moved");
TSL_ASSERT(offsetof(tsl_extent, height) == 4, "tsl_extent.height moved");

/*
 * A run of elements in the payload region following a record.
 *
 * offset is in bytes from the start of that region; count is in elements, so the element type is
 * implied by the field the span sits in. Validate both against the record's payload_len before
 * dereferencing: these arrive from the far side and a span that overruns is an out-of-bounds
 * read, not a short one.
 *
 * Mirrors `Span`.
 */
typedef struct tsl_span {
    /* Byte offset into the payload region. */
    uint32_t offset;
    /* Number of elements. */
    uint32_t count;
} tsl_span;

TSL_ASSERT(sizeof(tsl_span) == 8, "tsl_span size differs from the Rust definition");
TSL_ASSERT(TSL_ALIGNOF(tsl_span) == 4, "tsl_span alignment differs from the Rust definition");
TSL_ASSERT(offsetof(tsl_span, offset) == 0, "tsl_span.offset moved");
TSL_ASSERT(offsetof(tsl_span, count) == 4, "tsl_span.count moved");

/*
 * A reference into a refcounted geometry slab. Hold the slab until the driver's copy completes.
 *
 * Mirrors `SlabRef`.
 */
typedef struct tsl_slab_ref {
    /* Slab this data lives in. Across a mapping, an index into a slab_region's table of */
    /* slab_entry. */
    uint32_t slab;
    /* Byte offset within the slab. */
    uint32_t offset;
    /* Length in bytes. */
    uint32_t length;
} tsl_slab_ref;

TSL_ASSERT(sizeof(tsl_slab_ref) == 12, "tsl_slab_ref size differs from the Rust definition");
TSL_ASSERT(TSL_ALIGNOF(tsl_slab_ref) == 4, "tsl_slab_ref alignment differs from the Rust definition");
TSL_ASSERT(offsetof(tsl_slab_ref, slab) == 0, "tsl_slab_ref.slab moved");
TSL_ASSERT(offsetof(tsl_slab_ref, offset) == 4, "tsl_slab_ref.offset moved");
TSL_ASSERT(offsetof(tsl_slab_ref, length) == 8, "tsl_slab_ref.length moved");

/*
 * One slab's place in a packed slab region.
 *
 * A slab_ref names a slab by handle, which is only meaningful against something that maps it. In
 * process a consumer holds the slabs directly and never sees this; a consumer across a mapping
 * reads a region laid out as slab_region, then count of these, then the bytes they describe.
 * Every slab begins eight-aligned so its contents can be read at their natural alignment.
 *
 * slab_ref.slab is an index into that table, so a reference resolves to region +
 * entry[ref.slab].offset + ref.offset for ref.length bytes. Reject a handle that is not less
 * than slab_region.count: the table is the only thing that gives a handle a meaning, and a
 * handle it does not cover has none.
 *
 * Mirrors `SlabEntry`.
 */
typedef struct tsl_slab_entry {
    /* Byte offset of this slab's bytes from the start of the region. */
    uint64_t offset;
    /* Bytes in this slab. */
    uint64_t length;
} tsl_slab_entry;

TSL_ASSERT(sizeof(tsl_slab_entry) == 16, "tsl_slab_entry size differs from the Rust definition");
TSL_ASSERT(TSL_ALIGNOF(tsl_slab_entry) == 8, "tsl_slab_entry alignment differs from the Rust definition");
TSL_ASSERT(offsetof(tsl_slab_entry, offset) == 0, "tsl_slab_entry.offset moved");
TSL_ASSERT(offsetof(tsl_slab_entry, length) == 8, "tsl_slab_entry.length moved");

/*
 * The header of a packed slab region, followed by count slab_entry and then the bytes.
 *
 * abi_rev is here as well as on the ring because the two regions are mapped separately and may
 * be handed over by different means; a consumer that checked only the ring would accept a slab
 * region from another revision. Validate every entry against total_len before dereferencing it.
 *
 * Mirrors `SlabRegion`.
 */
typedef struct tsl_slab_region {
    /* ABI revision the producer packed this region with. */
    uint32_t abi_rev;
    /* Number of slab_entry following this header. */
    uint32_t count;
    /* Total bytes in the region, this header included. */
    uint64_t total_len;
} tsl_slab_region;

TSL_ASSERT(sizeof(tsl_slab_region) == 16, "tsl_slab_region size differs from the Rust definition");
TSL_ASSERT(TSL_ALIGNOF(tsl_slab_region) == 8, "tsl_slab_region alignment differs from the Rust definition");
TSL_ASSERT(offsetof(tsl_slab_region, abi_rev) == 0, "tsl_slab_region.abi_rev moved");
TSL_ASSERT(offsetof(tsl_slab_region, count) == 4, "tsl_slab_region.count moved");
TSL_ASSERT(offsetof(tsl_slab_region, total_len) == 8, "tsl_slab_region.total_len moved");

/*
 * One vertex attribute, as a binding rather than as bytes.
 *
 * binding of -1 means the geometry supplied an override the shader does not declare, and the
 * consumer must drop it. Bind declared_data_type, not data_type, with the supplied offset and
 * stride: binding the supplied type hands the shader a narrower attribute than it reads.
 *
 * Mirrors `AttributeDesc`.
 */
typedef struct tsl_attribute_desc {
    /* Shader-side attribute id. */
    uint32_t attr_id;
    /* Declared binding slot, or -1 to drop. */
    int32_t binding;
    /* Where the bytes are. */
    tsl_slab_ref source;
    /* Byte offset within a vertex. */
    uint32_t offset;
    /* First vertex. */
    uint32_t vertex_offset;
    /* Bytes between vertices. */
    uint32_t stride;
    /* tsl_attribute_data_type the buffer supplies. */
    uint8_t data_type;
    /* tsl_attribute_data_type the shader declares. Bind this one. */
    uint8_t declared_data_type;
    /* Must be zero. */
    uint8_t _pad[2];
} tsl_attribute_desc;

TSL_ASSERT(sizeof(tsl_attribute_desc) == 36, "tsl_attribute_desc size differs from the Rust definition");
TSL_ASSERT(TSL_ALIGNOF(tsl_attribute_desc) == 4, "tsl_attribute_desc alignment differs from the Rust definition");
TSL_ASSERT(offsetof(tsl_attribute_desc, attr_id) == 0, "tsl_attribute_desc.attr_id moved");
TSL_ASSERT(offsetof(tsl_attribute_desc, binding) == 4, "tsl_attribute_desc.binding moved");
TSL_ASSERT(offsetof(tsl_attribute_desc, source) == 8, "tsl_attribute_desc.source moved");
TSL_ASSERT(offsetof(tsl_attribute_desc, offset) == 20, "tsl_attribute_desc.offset moved");
TSL_ASSERT(offsetof(tsl_attribute_desc, vertex_offset) == 24, "tsl_attribute_desc.vertex_offset moved");
TSL_ASSERT(offsetof(tsl_attribute_desc, stride) == 28, "tsl_attribute_desc.stride moved");
TSL_ASSERT(offsetof(tsl_attribute_desc, data_type) == 32, "tsl_attribute_desc.data_type moved");
TSL_ASSERT(offsetof(tsl_attribute_desc, declared_data_type) == 33, "tsl_attribute_desc.declared_data_type moved");
TSL_ASSERT(offsetof(tsl_attribute_desc, _pad) == 34, "tsl_attribute_desc._pad moved");

/*
 * A contiguous index range with its own vertex base.
 *
 * Mirrors `Segment`.
 */
typedef struct tsl_segment {
    /* First vertex. */
    uint32_t vertex_offset;
    /* First index. */
    uint32_t index_offset;
    /* Vertex count. */
    uint32_t vertex_length;
    /* Index count. */
    uint32_t index_length;
} tsl_segment;

TSL_ASSERT(sizeof(tsl_segment) == 16, "tsl_segment size differs from the Rust definition");
TSL_ASSERT(TSL_ALIGNOF(tsl_segment) == 4, "tsl_segment alignment differs from the Rust definition");
TSL_ASSERT(offsetof(tsl_segment, vertex_offset) == 0, "tsl_segment.vertex_offset moved");
TSL_ASSERT(offsetof(tsl_segment, index_offset) == 4, "tsl_segment.index_offset moved");
TSL_ASSERT(offsetof(tsl_segment, vertex_length) == 8, "tsl_segment.vertex_length moved");
TSL_ASSERT(offsetof(tsl_segment, index_length) == 12, "tsl_segment.index_length moved");

/*
 * Binds a texture to a shader slot.
 *
 * Mirrors `TextureRef`.
 */
typedef struct tsl_texture_ref {
    /* Texture to bind. */
    uint64_t texture;
    /* Shader-side slot. */
    uint32_t slot;
    /* Must be zero. */
    uint32_t _pad;
} tsl_texture_ref;

TSL_ASSERT(sizeof(tsl_texture_ref) == 16, "tsl_texture_ref size differs from the Rust definition");
TSL_ASSERT(TSL_ALIGNOF(tsl_texture_ref) == 8, "tsl_texture_ref alignment differs from the Rust definition");
TSL_ASSERT(offsetof(tsl_texture_ref, texture) == 0, "tsl_texture_ref.texture moved");
TSL_ASSERT(offsetof(tsl_texture_ref, slot) == 8, "tsl_texture_ref.slot moved");
TSL_ASSERT(offsetof(tsl_texture_ref, _pad) == 12, "tsl_texture_ref._pad moved");

/*
 * Geometry, for the emission that carries it.
 *
 * Carries no view: one of these plus N tsl_view_use records replaces N copies of the whole
 * thing, which is why upload bandwidth scales with unique tiles rather than with view count.
 *
 * The id is dense from zero in every emission and is NOT stable across them. After a pan the
 * cover shifts and the ids are handed out in cover order, so the same id names a different tile.
 * A consumer that cached on it and skipped an upload it thought it already had would draw one
 * tile's geometry under another's matrix. The contract is coarser than tsl_view_release and
 * tsl_geometry_remove suggest: an emission of geometry replaces the previous set entire, and
 * nothing is released because nothing is retained.
 *
 * Mirrors `GeometryAdd`.
 */
typedef struct tsl_geometry_add {
    /* Id within this emission. Not stable across emissions -- see above. */
    uint64_t geometry;
    /* Distinguishes shader-family variants. */
    uint64_t permutation_key;
    /* Index buffer. */
    tsl_slab_ref indexes;
    /* Number of vertices. */
    uint32_t vertex_count;
    /* tsl_attribute_desc run. */
    tsl_span attrs;
    /* tsl_attribute_desc run, instanced. */
    tsl_span instance_attrs;
    /* tsl_segment run. */
    tsl_span segments;
    /* tsl_texture_ref run. */
    tsl_span texture_refs;
    /* tsl_builtin shader family. */
    int32_t builtin_shader;
    /* tsl_attribute_data_type of a vertex. */
    uint8_t vertex_type;
    /* tsl_add_reason. A steady stream of ATTRIBUTES_MODIFIED on a static scene is a bug. */
    uint8_t reason;
    /* Must be zero. */
    uint8_t _pad[2];
} tsl_geometry_add;

TSL_ASSERT(sizeof(tsl_geometry_add) == 72, "tsl_geometry_add size differs from the Rust definition");
TSL_ASSERT(TSL_ALIGNOF(tsl_geometry_add) == 8, "tsl_geometry_add alignment differs from the Rust definition");
TSL_ASSERT(offsetof(tsl_geometry_add, geometry) == 0, "tsl_geometry_add.geometry moved");
TSL_ASSERT(offsetof(tsl_geometry_add, permutation_key) == 8, "tsl_geometry_add.permutation_key moved");
TSL_ASSERT(offsetof(tsl_geometry_add, indexes) == 16, "tsl_geometry_add.indexes moved");
TSL_ASSERT(offsetof(tsl_geometry_add, vertex_count) == 28, "tsl_geometry_add.vertex_count moved");
TSL_ASSERT(offsetof(tsl_geometry_add, attrs) == 32, "tsl_geometry_add.attrs moved");
TSL_ASSERT(offsetof(tsl_geometry_add, instance_attrs) == 40, "tsl_geometry_add.instance_attrs moved");
TSL_ASSERT(offsetof(tsl_geometry_add, segments) == 48, "tsl_geometry_add.segments moved");
TSL_ASSERT(offsetof(tsl_geometry_add, texture_refs) == 56, "tsl_geometry_add.texture_refs moved");
TSL_ASSERT(offsetof(tsl_geometry_add, builtin_shader) == 64, "tsl_geometry_add.builtin_shader moved");
TSL_ASSERT(offsetof(tsl_geometry_add, vertex_type) == 68, "tsl_geometry_add.vertex_type moved");
TSL_ASSERT(offsetof(tsl_geometry_add, reason) == 69, "tsl_geometry_add.reason moved");
TSL_ASSERT(offsetof(tsl_geometry_add, _pad) == 70, "tsl_geometry_add._pad moved");

/*
 * Announces a process-scoped, refcounted mesh: an authored model the consumer's own loader
 * reads.
 *
 * Not a tsl_geometry_add, because that describes geometry the producer computed and names an
 * mbgl shader family for it. A model tile arrives authored and there is no such family for a PBR
 * mesh. The bytes travel whole and a glTF loader reads them.
 *
 * The id is in the same space as tsl_geometry_add's, so tsl_view_use, tsl_view_release and
 * tsl_geometry_remove bind, release and drop a mesh exactly as they do geometry. A consumer that
 * skips this envelope and later meets a tsl_view_use naming the id has a protocol fault: a style
 * with a model layer cannot be drawn without a mesh loader.
 *
 * Placement is not here. The tile-to-clip matrix is per view and per frame; this record is
 * neither, and the matrix travels as a tsl_ubo_update like every other layer's.
 *
 * Mirrors `MeshAdd`.
 */
typedef struct tsl_mesh_add {
    /* Process-wide id, shared with tsl_geometry_add. */
    uint64_t mesh;
    /* The asset's bytes. A slab reference rather than an inline payload: a model tile is */
    /* hundreds of kilobytes and the ring is sized by envelope count. It is also what makes the */
    /* hand-off zero-copy -- a glTF loader parses straight from this memory, and the consumer */
    /* holds the slab alive until it is done. */
    tsl_slab_ref bytes;
    /* tsl_mesh_format of the bytes. */
    uint8_t format;
    /* tsl_add_reason. A mesh is announced once and not modified in place. */
    uint8_t reason;
    /* Must be zero. */
    uint8_t _pad[2];
} tsl_mesh_add;

TSL_ASSERT(sizeof(tsl_mesh_add) == 24, "tsl_mesh_add size differs from the Rust definition");
TSL_ASSERT(TSL_ALIGNOF(tsl_mesh_add) == 8, "tsl_mesh_add alignment differs from the Rust definition");
TSL_ASSERT(offsetof(tsl_mesh_add, mesh) == 0, "tsl_mesh_add.mesh moved");
TSL_ASSERT(offsetof(tsl_mesh_add, bytes) == 8, "tsl_mesh_add.bytes moved");
TSL_ASSERT(offsetof(tsl_mesh_add, format) == 20, "tsl_mesh_add.format moved");
TSL_ASSERT(offsetof(tsl_mesh_add, reason) == 21, "tsl_mesh_add.reason moved");
TSL_ASSERT(offsetof(tsl_mesh_add, _pad) == 22, "tsl_mesh_add._pad moved");

/*
 * Drops shared geometry once no view holds it.
 *
 * Mirrors `GeometryRemove`.
 */
typedef struct tsl_geometry_remove {
    /* Geometry to drop. */
    uint64_t geometry;
} tsl_geometry_remove;

TSL_ASSERT(sizeof(tsl_geometry_remove) == 8, "tsl_geometry_remove size differs from the Rust definition");
TSL_ASSERT(TSL_ALIGNOF(tsl_geometry_remove) == 8, "tsl_geometry_remove alignment differs from the Rust definition");
TSL_ASSERT(offsetof(tsl_geometry_remove, geometry) == 0, "tsl_geometry_remove.geometry moved");

/*
 * Declares a view and its configuration.
 *
 * Ordered ahead of any tsl_view_use naming the view, and re-emitted when the configuration
 * changes rather than repeated per use. A tsl_view_use naming an undeclared view is a protocol
 * fault.
 *
 * Mirrors `ViewDeclare`.
 */
typedef struct tsl_view_declare {
    /* View being declared. */
    uint32_t view;
    /* tsl_camera_mode. Per view, not per use. */
    uint8_t camera_mode;
    /* Must be zero. Reserved for the per-view maxzoom clamp and view class. */
    uint8_t _reserved[3];
} tsl_view_declare;

TSL_ASSERT(sizeof(tsl_view_declare) == 8, "tsl_view_declare size differs from the Rust definition");
TSL_ASSERT(TSL_ALIGNOF(tsl_view_declare) == 4, "tsl_view_declare alignment differs from the Rust definition");
TSL_ASSERT(offsetof(tsl_view_declare, view) == 0, "tsl_view_declare.view moved");
TSL_ASSERT(offsetof(tsl_view_declare, camera_mode) == 4, "tsl_view_declare.camera_mode moved");
TSL_ASSERT(offsetof(tsl_view_declare, _reserved) == 5, "tsl_view_declare._reserved moved");

/*
 * Drops a view and everything scoped to it: its scene, uniform buffers, stencil sets and
 * reverse-channel slot. Geometry it was using is refcounted and process-scoped, so it is not
 * dropped with the view.
 *
 * Mirrors `ViewUndeclare`.
 */
typedef struct tsl_view_undeclare {
    /* View being dropped. */
    uint32_t view;
} tsl_view_undeclare;

TSL_ASSERT(sizeof(tsl_view_undeclare) == 4, "tsl_view_undeclare size differs from the Rust definition");
TSL_ASSERT(TSL_ALIGNOF(tsl_view_undeclare) == 4, "tsl_view_undeclare alignment differs from the Rust definition");
TSL_ASSERT(offsetof(tsl_view_undeclare, view) == 0, "tsl_view_undeclare.view moved");

/*
 * Binds shared geometry into one view's draw order.
 *
 * Carries nothing about the view itself; see tsl_view_declare.
 *
 * Mirrors `ViewUse`.
 */
typedef struct tsl_view_use {
    /* Geometry being used. */
    uint64_t geometry;
    /* View using it. */
    uint32_t view;
    /* Layer group. */
    int32_t layer_index;
    /* Order within the layer. */
    int32_t sub_layer_index;
    /* Tile covered, when has_tile is set. */
    tsl_tile_id tile;
    /* tsl_render_pass mask. */
    uint8_t render_pass;
    /* tsl_draw_flags mask. */
    uint8_t draw_flags;
    /* Non-zero when tile is meaningful. */
    uint8_t has_tile;
    /* Must be zero. */
    uint8_t _pad;
} tsl_view_use;

TSL_ASSERT(sizeof(tsl_view_use) == 40, "tsl_view_use size differs from the Rust definition");
TSL_ASSERT(TSL_ALIGNOF(tsl_view_use) == 8, "tsl_view_use alignment differs from the Rust definition");
TSL_ASSERT(offsetof(tsl_view_use, geometry) == 0, "tsl_view_use.geometry moved");
TSL_ASSERT(offsetof(tsl_view_use, view) == 8, "tsl_view_use.view moved");
TSL_ASSERT(offsetof(tsl_view_use, layer_index) == 12, "tsl_view_use.layer_index moved");
TSL_ASSERT(offsetof(tsl_view_use, sub_layer_index) == 16, "tsl_view_use.sub_layer_index moved");
TSL_ASSERT(offsetof(tsl_view_use, tile) == 20, "tsl_view_use.tile moved");
TSL_ASSERT(offsetof(tsl_view_use, render_pass) == 32, "tsl_view_use.render_pass moved");
TSL_ASSERT(offsetof(tsl_view_use, draw_flags) == 33, "tsl_view_use.draw_flags moved");
TSL_ASSERT(offsetof(tsl_view_use, has_tile) == 34, "tsl_view_use.has_tile moved");
TSL_ASSERT(offsetof(tsl_view_use, _pad) == 35, "tsl_view_use._pad moved");

/*
 * Releases one view's use of shared geometry.
 *
 * Mirrors `ViewRelease`.
 */
typedef struct tsl_view_release {
    /* Geometry being released. */
    uint64_t geometry;
    /* View releasing it. */
    uint32_t view;
    /* Must be zero. */
    uint32_t _pad;
} tsl_view_release;

TSL_ASSERT(sizeof(tsl_view_release) == 16, "tsl_view_release size differs from the Rust definition");
TSL_ASSERT(TSL_ALIGNOF(tsl_view_release) == 8, "tsl_view_release alignment differs from the Rust definition");
TSL_ASSERT(offsetof(tsl_view_release, geometry) == 0, "tsl_view_release.geometry moved");
TSL_ASSERT(offsetof(tsl_view_release, view) == 8, "tsl_view_release.view moved");
TSL_ASSERT(offsetof(tsl_view_release, _pad) == 12, "tsl_view_release._pad moved");

/*
 * An absolute write to a consolidated uniform buffer.
 *
 * Absolute, never a delta, which is what makes latest-wins coalescing exact. layer_index of -1
 * means a frame-wide buffer belonging to no layer.
 *
 * Mirrors `UboUpdate`.
 */
typedef struct tsl_ubo_update {
    /* View this buffer belongs to. */
    uint32_t view;
    /* Layer group, or -1 for frame-wide. */
    int32_t layer_index;
    /* Buffer slot. */
    uint32_t slot;
    /* Must be zero. */
    uint32_t _pad;
    /* Buffer bytes; count is a byte count. */
    tsl_span data;
} tsl_ubo_update;

TSL_ASSERT(sizeof(tsl_ubo_update) == 24, "tsl_ubo_update size differs from the Rust definition");
TSL_ASSERT(TSL_ALIGNOF(tsl_ubo_update) == 4, "tsl_ubo_update alignment differs from the Rust definition");
TSL_ASSERT(offsetof(tsl_ubo_update, view) == 0, "tsl_ubo_update.view moved");
TSL_ASSERT(offsetof(tsl_ubo_update, layer_index) == 4, "tsl_ubo_update.layer_index moved");
TSL_ASSERT(offsetof(tsl_ubo_update, slot) == 8, "tsl_ubo_update.slot moved");
TSL_ASSERT(offsetof(tsl_ubo_update, _pad) == 12, "tsl_ubo_update._pad moved");
TSL_ASSERT(offsetof(tsl_ubo_update, data) == 16, "tsl_ubo_update.data moved");

/*
 * New pixels for a process-scoped texture.
 *
 * Carries no view: one texture serves every view that draws with it. rect_count of zero means a
 * whole-texture upload.
 *
 * Mirrors `TextureUpdate`.
 */
typedef struct tsl_texture_update {
    /* Texture being written. */
    uint64_t texture;
    /* Full texture dimensions. */
    tsl_extent size;
    /* Dirty regions; first rect_count are meaningful. */
    tsl_rect rects[TSL_TEXTURE_RECT_CAP];
    /* Pixel bytes; count is a byte count. */
    tsl_span pixels;
    /* tsl_texture_pixel_type. */
    uint8_t format;
    /* Meaningful entries in rects; zero means whole texture. */
    uint8_t rect_count;
    /* Must be zero. */
    uint8_t _pad[2];
} tsl_texture_update;

TSL_ASSERT(sizeof(tsl_texture_update) == 64, "tsl_texture_update size differs from the Rust definition");
TSL_ASSERT(TSL_ALIGNOF(tsl_texture_update) == 8, "tsl_texture_update alignment differs from the Rust definition");
TSL_ASSERT(offsetof(tsl_texture_update, texture) == 0, "tsl_texture_update.texture moved");
TSL_ASSERT(offsetof(tsl_texture_update, size) == 8, "tsl_texture_update.size moved");
TSL_ASSERT(offsetof(tsl_texture_update, rects) == 16, "tsl_texture_update.rects moved");
TSL_ASSERT(offsetof(tsl_texture_update, pixels) == 48, "tsl_texture_update.pixels moved");
TSL_ASSERT(offsetof(tsl_texture_update, format) == 56, "tsl_texture_update.format moved");
TSL_ASSERT(offsetof(tsl_texture_update, rect_count) == 57, "tsl_texture_update.rect_count moved");
TSL_ASSERT(offsetof(tsl_texture_update, _pad) == 58, "tsl_texture_update._pad moved");

/*
 * One tile of a clip set, with the matrix placing its mask quad.
 *
 * The matrix travels with the tile because the consumer draws the quad itself and must not
 * derive it from a content drawable's matrix, which carries the layer's translate and would put
 * the mask where the content is not.
 *
 * Mirrors `StencilTile`.
 */
typedef struct tsl_stencil_tile {
    /* Column-major tile-to-clip. */
    float matrix[16];
    /* Tile this mask covers. */
    tsl_tile_id tile;
} tsl_stencil_tile;

TSL_ASSERT(sizeof(tsl_stencil_tile) == 76, "tsl_stencil_tile size differs from the Rust definition");
TSL_ASSERT(TSL_ALIGNOF(tsl_stencil_tile) == 4, "tsl_stencil_tile alignment differs from the Rust definition");
TSL_ASSERT(offsetof(tsl_stencil_tile, matrix) == 0, "tsl_stencil_tile.matrix moved");
TSL_ASSERT(offsetof(tsl_stencil_tile, tile) == 64, "tsl_stencil_tile.tile moved");

/*
 * The tile set a layer group wants clipped.
 *
 * Stencil reference values are deliberately absent: the consumer assigns its own and keys them
 * by tile.
 *
 * Mirrors `StencilTiles`.
 */
typedef struct tsl_stencil_tiles {
    /* View this clip set belongs to. */
    uint32_t view;
    /* Layer group being clipped. */
    int32_t layer_index;
    /* tsl_stencil_tile run. */
    tsl_span tiles;
} tsl_stencil_tiles;

TSL_ASSERT(sizeof(tsl_stencil_tiles) == 16, "tsl_stencil_tiles size differs from the Rust definition");
TSL_ASSERT(TSL_ALIGNOF(tsl_stencil_tiles) == 4, "tsl_stencil_tiles alignment differs from the Rust definition");
TSL_ASSERT(offsetof(tsl_stencil_tiles, view) == 0, "tsl_stencil_tiles.view moved");
TSL_ASSERT(offsetof(tsl_stencil_tiles, layer_index) == 4, "tsl_stencil_tiles.layer_index moved");
TSL_ASSERT(offsetof(tsl_stencil_tiles, tiles) == 8, "tsl_stencil_tiles.tiles moved");

/*
 * One geometry's position in a view's painter order.
 *
 * Mirrors `OrderEntry`.
 */
typedef struct tsl_order_entry {
    /* Geometry being drawn. */
    uint64_t geometry;
    /* Sort key within the layer. */
    int64_t draw_priority;
    /* Layer group. */
    uint32_t layer_index;
    /* Order within the layer. */
    int32_t sub_layer_index;
    /* Slot in the layer's consolidated buffer. */
    uint32_t ubo_index;
    /* tsl_render_pass this entry draws in. */
    uint8_t pass;
    /* Must be zero. */
    uint8_t _pad[3];
} tsl_order_entry;

TSL_ASSERT(sizeof(tsl_order_entry) == 32, "tsl_order_entry size differs from the Rust definition");
TSL_ASSERT(TSL_ALIGNOF(tsl_order_entry) == 8, "tsl_order_entry alignment differs from the Rust definition");
TSL_ASSERT(offsetof(tsl_order_entry, geometry) == 0, "tsl_order_entry.geometry moved");
TSL_ASSERT(offsetof(tsl_order_entry, draw_priority) == 8, "tsl_order_entry.draw_priority moved");
TSL_ASSERT(offsetof(tsl_order_entry, layer_index) == 16, "tsl_order_entry.layer_index moved");
TSL_ASSERT(offsetof(tsl_order_entry, sub_layer_index) == 20, "tsl_order_entry.sub_layer_index moved");
TSL_ASSERT(offsetof(tsl_order_entry, ubo_index) == 24, "tsl_order_entry.ubo_index moved");
TSL_ASSERT(offsetof(tsl_order_entry, pass) == 28, "tsl_order_entry.pass moved");
TSL_ASSERT(offsetof(tsl_order_entry, _pad) == 29, "tsl_order_entry._pad moved");

/*
 * A view's draw order, emitted only when it differs from the last one.
 *
 * Mirrors `OrderUpdate`.
 */
typedef struct tsl_order_update {
    /* Epoch this order establishes. */
    uint64_t order_epoch;
    /* View this order belongs to. */
    uint32_t view;
    /* Must be zero. */
    uint32_t _pad;
    /* tsl_order_entry run, in draw order. */
    tsl_span entries;
} tsl_order_update;

TSL_ASSERT(sizeof(tsl_order_update) == 24, "tsl_order_update size differs from the Rust definition");
TSL_ASSERT(TSL_ALIGNOF(tsl_order_update) == 8, "tsl_order_update alignment differs from the Rust definition");
TSL_ASSERT(offsetof(tsl_order_update, order_epoch) == 0, "tsl_order_update.order_epoch moved");
TSL_ASSERT(offsetof(tsl_order_update, view) == 8, "tsl_order_update.view moved");
TSL_ASSERT(offsetof(tsl_order_update, _pad) == 12, "tsl_order_update._pad moved");
TSL_ASSERT(offsetof(tsl_order_update, entries) == 16, "tsl_order_update.entries moved");

/*
 * The style's light.
 *
 * Mirrors `Light`.
 */
typedef struct tsl_light {
    /* Direction towards the light, cartesian. */
    double direction[3];
    /* Light color, RGBA. */
    double color[4];
    /* Light intensity. */
    double intensity;
    /* Non-zero when anchored to the map rather than the viewport. */
    uint8_t anchored_to_map;
    /* Must be zero. */
    uint8_t _pad[7];
} tsl_light;

TSL_ASSERT(sizeof(tsl_light) == 72, "tsl_light size differs from the Rust definition");
TSL_ASSERT(TSL_ALIGNOF(tsl_light) == 8, "tsl_light alignment differs from the Rust definition");
TSL_ASSERT(offsetof(tsl_light, direction) == 0, "tsl_light.direction moved");
TSL_ASSERT(offsetof(tsl_light, color) == 24, "tsl_light.color moved");
TSL_ASSERT(offsetof(tsl_light, intensity) == 56, "tsl_light.intensity moved");
TSL_ASSERT(offsetof(tsl_light, anchored_to_map) == 64, "tsl_light.anchored_to_map moved");
TSL_ASSERT(offsetof(tsl_light, _pad) == 65, "tsl_light._pad moved");

/*
 * A view's camera and frame-wide parameters.
 *
 * Apply only once the referenced order_epoch is held; otherwise hold the camera until its
 * tsl_order_update arrives.
 *
 * In consumer-camera mode proj_matrix, center_zoom0, bearing and pitch are advisory — the
 * producer computed them from a camera read back one frame stale. The rest stay authoritative
 * because the producer is the only side that knows them.
 *
 * center_zoom0 is the map center at zoom zero, 0..512 regardless of the map's zoom, scale-free
 * on purpose. Multiplying it by a frame's zoom scale before sending couples it to that frame and
 * makes a consumer at a slightly different zoom look where the tiles are not.
 *
 * Mirrors `CameraUpdate`.
 */
typedef struct tsl_camera_update {
    /* World-to-clip, column-major. */
    double proj_matrix[16];
    /* Map center at zoom zero. Scale-free. */
    double center_zoom0[2];
    /* Bearing in degrees. */
    double bearing;
    /* Pitch in degrees. */
    double pitch;
    /* World pixels per meter. Omit it and heights come out wrong by its reciprocal. */
    double pixels_per_meter;
    /* Style light. */
    tsl_light light;
    /* Frame this camera belongs to. */
    uint64_t frame_no;
    /* Order this camera was computed against. */
    uint64_t order_epoch;
    /* View this camera belongs to. */
    uint32_t view;
    /* Draw-order index where the opaque pass ends. */
    uint32_t opaque_pass_cutoff;
    /* Depth range. */
    float depth_range_size;
    /* Must be zero. */
    uint32_t _pad;
} tsl_camera_update;

TSL_ASSERT(sizeof(tsl_camera_update) == 272, "tsl_camera_update size differs from the Rust definition");
TSL_ASSERT(TSL_ALIGNOF(tsl_camera_update) == 8, "tsl_camera_update alignment differs from the Rust definition");
TSL_ASSERT(offsetof(tsl_camera_update, proj_matrix) == 0, "tsl_camera_update.proj_matrix moved");
TSL_ASSERT(offsetof(tsl_camera_update, center_zoom0) == 128, "tsl_camera_update.center_zoom0 moved");
TSL_ASSERT(offsetof(tsl_camera_update, bearing) == 144, "tsl_camera_update.bearing moved");
TSL_ASSERT(offsetof(tsl_camera_update, pitch) == 152, "tsl_camera_update.pitch moved");
TSL_ASSERT(offsetof(tsl_camera_update, pixels_per_meter) == 160, "tsl_camera_update.pixels_per_meter moved");
TSL_ASSERT(offsetof(tsl_camera_update, light) == 168, "tsl_camera_update.light moved");
TSL_ASSERT(offsetof(tsl_camera_update, frame_no) == 240, "tsl_camera_update.frame_no moved");
TSL_ASSERT(offsetof(tsl_camera_update, order_epoch) == 248, "tsl_camera_update.order_epoch moved");
TSL_ASSERT(offsetof(tsl_camera_update, view) == 256, "tsl_camera_update.view moved");
TSL_ASSERT(offsetof(tsl_camera_update, opaque_pass_cutoff) == 260, "tsl_camera_update.opaque_pass_cutoff moved");
TSL_ASSERT(offsetof(tsl_camera_update, depth_range_size) == 264, "tsl_camera_update.depth_range_size moved");
TSL_ASSERT(offsetof(tsl_camera_update, _pad) == 268, "tsl_camera_update._pad moved");

/*
 * Fixed prefix of every record on the ring.
 *
 * A record is this header, then record_len bytes of fixed envelope, then payload_len bytes of
 * payload, the whole padded to TSL_RECORD_ALIGN. Records never straddle the buffer's wrap: one
 * that would not fit contiguously is preceded by a record with TSL_RECORD_FLAG_SKIP set,
 * covering the remainder.
 *
 * Mirrors `RecordHeader`.
 */
typedef struct tsl_record_header {
    /* tsl_envelope_kind, or zero for a skip record. */
    uint16_t kind;
    /* TSL_RECORD_FLAG_SKIP, or zero. */
    uint16_t flags;
    /* Bytes of fixed envelope record. */
    uint32_t record_len;
    /* Bytes of payload region. */
    uint32_t payload_len;
    /* Total bytes, header included. */
    uint32_t total_len;
} tsl_record_header;

TSL_ASSERT(sizeof(tsl_record_header) == 16, "tsl_record_header size differs from the Rust definition");
TSL_ASSERT(TSL_ALIGNOF(tsl_record_header) == 4, "tsl_record_header alignment differs from the Rust definition");
TSL_ASSERT(offsetof(tsl_record_header, kind) == 0, "tsl_record_header.kind moved");
TSL_ASSERT(offsetof(tsl_record_header, flags) == 2, "tsl_record_header.flags moved");
TSL_ASSERT(offsetof(tsl_record_header, record_len) == 4, "tsl_record_header.record_len moved");
TSL_ASSERT(offsetof(tsl_record_header, payload_len) == 8, "tsl_record_header.payload_len moved");
TSL_ASSERT(offsetof(tsl_record_header, total_len) == 12, "tsl_record_header.total_len moved");

/*
 * Control block at the head of the shared region, followed by capacity data bytes.
 *
 * head and tail are free-running byte counters, not indices, so full and empty are never
 * ambiguous. Access them atomically: the producer releases head after writing bytes, the
 * consumer acquires head before reading them and releases tail after. They are declared as plain
 * integers so this header stays includable from C and C++ alike; the atomicity is a protocol
 * obligation, not a type.
 *
 * Mirrors `RingControl`.
 */
typedef struct tsl_ring_control {
    /* ABI revision the producer wrote this region with. */
    uint32_t abi_rev;
    /* Must be zero. */
    uint32_t _pad0;
    /* Bytes in the data region. Always a power of two. */
    uint64_t capacity;
    /* Must be zero. Keeps the counters off this line. */
    uint8_t _pad1[112];
    /* Bytes ever written. Producer releases, consumer acquires. */
    uint64_t head;
    /* Must be zero. Keeps the counters off each other's line. */
    uint8_t _pad2[120];
    /* Bytes ever consumed. Consumer releases, producer acquires. */
    uint64_t tail;
    /* Must be zero. */
    uint8_t _pad3[120];
} tsl_ring_control;

TSL_ASSERT(sizeof(tsl_ring_control) == 384, "tsl_ring_control size differs from the Rust definition");
TSL_ASSERT(TSL_ALIGNOF(tsl_ring_control) == 8, "tsl_ring_control alignment differs from the Rust definition");
TSL_ASSERT(offsetof(tsl_ring_control, abi_rev) == 0, "tsl_ring_control.abi_rev moved");
TSL_ASSERT(offsetof(tsl_ring_control, _pad0) == 4, "tsl_ring_control._pad0 moved");
TSL_ASSERT(offsetof(tsl_ring_control, capacity) == 8, "tsl_ring_control.capacity moved");
TSL_ASSERT(offsetof(tsl_ring_control, _pad1) == 16, "tsl_ring_control._pad1 moved");
TSL_ASSERT(offsetof(tsl_ring_control, head) == 128, "tsl_ring_control.head moved");
TSL_ASSERT(offsetof(tsl_ring_control, _pad2) == 136, "tsl_ring_control._pad2 moved");
TSL_ASSERT(offsetof(tsl_ring_control, tail) == 256, "tsl_ring_control.tail moved");
TSL_ASSERT(offsetof(tsl_ring_control, _pad3) == 264, "tsl_ring_control._pad3 moved");

/*
 * One view's slot in the consumer-to-producer strip (DR-10).
 *
 * Guarded by a seqlock. A writer increments seq to an odd value, fences, writes the payload,
 * then stores the next even value with release. A reader takes seq, reads the payload, takes seq
 * again, and retries unless both reads are equal and even. Skipping the retry yields a torn
 * camera -- a center from one frame with a zoom from the next -- which reads as a view that
 * lurches rather than one that is wrong.
 *
 * The doubles travel as their bit patterns, so this stays a plain-integer struct and the header
 * stays includable from C and C++ alike.
 *
 * Mirrors `ViewSlot`.
 */
typedef struct tsl_view_slot {
    /* Seqlock counter. Even is stable; odd means a write is in progress. */
    uint32_t seq;
    /* TSL_VIEW_FLAG_PUBLISHED and TSL_VIEW_FLAG_VISIBLE. */
    uint32_t flags;
    /* Map center at zoom zero, x, as the bits of a double. Scale-free, 0..512. */
    uint64_t center_x;
    /* Map center at zoom zero, y, as the bits of a double. */
    uint64_t center_y;
    /* Fractional zoom, as the bits of a double. */
    uint64_t zoom;
    /* Bearing in degrees, as the bits of a double. */
    uint64_t bearing;
    /* Pitch in degrees, as the bits of a double. */
    uint64_t pitch;
    /* Viewport width in pixels. */
    uint32_t viewport_width;
    /* Viewport height in pixels. */
    uint32_t viewport_height;
} tsl_view_slot;

TSL_ASSERT(sizeof(tsl_view_slot) == 56, "tsl_view_slot size differs from the Rust definition");
TSL_ASSERT(TSL_ALIGNOF(tsl_view_slot) == 8, "tsl_view_slot alignment differs from the Rust definition");
TSL_ASSERT(offsetof(tsl_view_slot, seq) == 0, "tsl_view_slot.seq moved");
TSL_ASSERT(offsetof(tsl_view_slot, flags) == 4, "tsl_view_slot.flags moved");
TSL_ASSERT(offsetof(tsl_view_slot, center_x) == 8, "tsl_view_slot.center_x moved");
TSL_ASSERT(offsetof(tsl_view_slot, center_y) == 16, "tsl_view_slot.center_y moved");
TSL_ASSERT(offsetof(tsl_view_slot, zoom) == 24, "tsl_view_slot.zoom moved");
TSL_ASSERT(offsetof(tsl_view_slot, bearing) == 32, "tsl_view_slot.bearing moved");
TSL_ASSERT(offsetof(tsl_view_slot, pitch) == 40, "tsl_view_slot.pitch moved");
TSL_ASSERT(offsetof(tsl_view_slot, viewport_width) == 48, "tsl_view_slot.viewport_width moved");
TSL_ASSERT(offsetof(tsl_view_slot, viewport_height) == 52, "tsl_view_slot.viewport_height moved");

/*
 * The consumer-to-producer strip (DR-10), living in the shared region beside the ring.
 *
 * The consumer writes every field here and the producer reads them, which is the opposite
 * direction to everything else in this header. It carries what the producer cannot know on its
 * own: which geometry has actually reached the GPU, and where each view's camera is under
 * consumer-camera mode.
 *
 * Mirrors `ReverseChannel`.
 */
typedef struct tsl_reverse_channel {
    /* Ring position whose geometry the consumer has uploaded to the GPU. Distinct from the */
    /* ring's tail, which says only that the bytes were read: an ancestor tile may be released */
    /* once its descendants are on the GPU, not once their envelopes were parsed. */
    uint64_t acked_geometry;
    /* One slot per view, indexed by view id. Slots past the declared views stay unpublished. */
    tsl_view_slot views[TSL_MAX_VIEWS];
} tsl_reverse_channel;

TSL_ASSERT(sizeof(tsl_reverse_channel) == 456, "tsl_reverse_channel size differs from the Rust definition");
TSL_ASSERT(TSL_ALIGNOF(tsl_reverse_channel) == 8, "tsl_reverse_channel alignment differs from the Rust definition");
TSL_ASSERT(offsetof(tsl_reverse_channel, acked_geometry) == 0, "tsl_reverse_channel.acked_geometry moved");
TSL_ASSERT(offsetof(tsl_reverse_channel, views) == 8, "tsl_reverse_channel.views moved");

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* TESSELLA_CAPTURE_ABI_H */
