// Generated by `cargo run -p abi-header`. Do not edit by hand.
//
// The tessella capture-stream ABI, revision 2, as offsets.
//
// The Rust definitions in tessella-capture-abi are the source of truth, and these numbers came
// from `size_of`, `align_of` and `offset_of!` on them at generation time -- the same call that
// wrote the C header's static assertions. A consumer reading the ring out of a
// `WebAssembly.Memory` has no compiler to check its arithmetic, so this is the only thing
// standing between it and a silent misread.

export const ABI_REV = 2;
export const RECORD_ALIGN = 16;
export const PAYLOAD_ALIGN = 8;
export const RECORD_FLAG_SKIP = 1;

/** Envelope kinds carried on the ring. */
export const KIND = Object.freeze({
  GEOMETRY_ADD: 1,
  GEOMETRY_REMOVE: 2,
  VIEW_USE: 3,
  VIEW_RELEASE: 4,
  UBO_UPDATE: 5,
  TEXTURE_UPDATE: 6,
  CAMERA_UPDATE: 7,
  ORDER_UPDATE: 8,
  STENCIL_TILES: 9,
  VIEW_DECLARE: 10,
  VIEW_UNDECLARE: 11,
  MESH_ADD: 12,
});

/** Every struct's width, alignment and field offsets, in bytes. */
export const LAYOUT = Object.freeze({
  tsl_tile_id: {
    size: 12, align: 4,
    at: {
      x: 0,
      y: 4,
      z: 8,
      overscaled_z: 9,
      wrap: 10,
    },
  },
  tsl_rect: {
    size: 8, align: 2,
    at: {
      x: 0,
      y: 2,
      w: 4,
      h: 6,
    },
  },
  tsl_extent: {
    size: 8, align: 4,
    at: {
      width: 0,
      height: 4,
    },
  },
  tsl_span: {
    size: 8, align: 4,
    at: {
      offset: 0,
      count: 4,
    },
  },
  tsl_slab_ref: {
    size: 12, align: 4,
    at: {
      slab: 0,
      offset: 4,
      length: 8,
    },
  },
  tsl_slab_entry: {
    size: 16, align: 8,
    at: {
      offset: 0,
      length: 8,
    },
  },
  tsl_slab_region: {
    size: 16, align: 8,
    at: {
      abi_rev: 0,
      count: 4,
      total_len: 8,
    },
  },
  tsl_attribute_desc: {
    size: 36, align: 4,
    at: {
      attr_id: 0,
      binding: 4,
      source: 8,
      offset: 20,
      vertex_offset: 24,
      stride: 28,
      data_type: 32,
      declared_data_type: 33,
      _pad: 34,
    },
  },
  tsl_segment: {
    size: 16, align: 4,
    at: {
      vertex_offset: 0,
      index_offset: 4,
      vertex_length: 8,
      index_length: 12,
    },
  },
  tsl_texture_ref: {
    size: 16, align: 8,
    at: {
      texture: 0,
      slot: 8,
      filter: 12,
    },
  },
  tsl_geometry_add: {
    size: 72, align: 8,
    at: {
      geometry: 0,
      permutation_key: 8,
      indexes: 16,
      vertex_count: 28,
      attrs: 32,
      instance_attrs: 40,
      segments: 48,
      texture_refs: 56,
      builtin_shader: 64,
      vertex_type: 68,
      reason: 69,
      _pad: 70,
    },
  },
  tsl_mesh_add: {
    size: 24, align: 8,
    at: {
      mesh: 0,
      bytes: 8,
      format: 20,
      reason: 21,
      _pad: 22,
    },
  },
  tsl_geometry_remove: {
    size: 8, align: 8,
    at: {
      geometry: 0,
    },
  },
  tsl_view_declare: {
    size: 8, align: 4,
    at: {
      view: 0,
      camera_mode: 4,
      _reserved: 5,
    },
  },
  tsl_view_undeclare: {
    size: 4, align: 4,
    at: {
      view: 0,
    },
  },
  tsl_view_use: {
    size: 40, align: 8,
    at: {
      geometry: 0,
      view: 8,
      layer_index: 12,
      sub_layer_index: 16,
      tile: 20,
      render_pass: 32,
      draw_flags: 33,
      has_tile: 34,
      _pad: 35,
    },
  },
  tsl_view_release: {
    size: 16, align: 8,
    at: {
      geometry: 0,
      view: 8,
      _pad: 12,
    },
  },
  tsl_ubo_update: {
    size: 24, align: 4,
    at: {
      view: 0,
      layer_index: 4,
      slot: 8,
      _pad: 12,
      data: 16,
    },
  },
  tsl_texture_update: {
    size: 64, align: 8,
    at: {
      texture: 0,
      size: 8,
      rects: 16,
      pixels: 48,
      format: 56,
      rect_count: 57,
      _pad: 58,
    },
  },
  tsl_stencil_tile: {
    size: 76, align: 4,
    at: {
      matrix: 0,
      tile: 64,
    },
  },
  tsl_stencil_tiles: {
    size: 16, align: 4,
    at: {
      view: 0,
      layer_index: 4,
      tiles: 8,
    },
  },
  tsl_order_entry: {
    size: 32, align: 8,
    at: {
      geometry: 0,
      draw_priority: 8,
      layer_index: 16,
      sub_layer_index: 20,
      ubo_index: 24,
      pass: 28,
      _pad: 29,
    },
  },
  tsl_order_update: {
    size: 24, align: 8,
    at: {
      order_epoch: 0,
      view: 8,
      _pad: 12,
      entries: 16,
    },
  },
  tsl_light: {
    size: 72, align: 8,
    at: {
      direction: 0,
      color: 24,
      intensity: 56,
      anchored_to_map: 64,
      _pad: 65,
    },
  },
  tsl_camera_update: {
    size: 272, align: 8,
    at: {
      proj_matrix: 0,
      center_zoom0: 128,
      bearing: 144,
      pitch: 152,
      pixels_per_meter: 160,
      light: 168,
      frame_no: 240,
      order_epoch: 248,
      view: 256,
      opaque_pass_cutoff: 260,
      depth_range_size: 264,
      _pad: 268,
    },
  },
  tsl_record_header: {
    size: 16, align: 4,
    at: {
      kind: 0,
      flags: 2,
      record_len: 4,
      payload_len: 8,
      total_len: 12,
    },
  },
  tsl_ring_control: {
    size: 384, align: 8,
    at: {
      abi_rev: 0,
      _pad0: 4,
      capacity: 8,
      _pad1: 16,
      head: 128,
      _pad2: 136,
      tail: 256,
      _pad3: 264,
    },
  },
  tsl_view_slot: {
    size: 56, align: 8,
    at: {
      seq: 0,
      flags: 4,
      center_x: 8,
      center_y: 16,
      zoom: 24,
      bearing: 32,
      pitch: 40,
      viewport_width: 48,
      viewport_height: 52,
    },
  },
  tsl_reverse_channel: {
    size: 456, align: 8,
    at: {
      acked_geometry: 0,
      views: 8,
    },
  },
});
